version: '3'
services:
  mysql:
   container_name: docmysql
   image: mysql/mysql-server:5.7
   ports:
    - "3306:3306"
   environment:
    MYSQL_USER: alex
    MYSQL_PASSWORD: pass
    MYSQL_DATABASE: db_cars
    MYSQL_ROOT_PASSWORD: root
    MYSQL_ROOT_HOST: '%'
  
  app:
   container_name: docapp
   build: ./lab
   working_dir: /lab
   expose:
    - "8080"
   volumes:
    - ./lab:/lab
    - ~/.m2:/root/.m2
   command: mvn clean spring-boot:run
   depends_on:
    - mysql

  nginx:
   container_name: docnginx
   image: nginx:1.13
   restart: always
   ports:
   - 80:80
   - 443:443
   volumes:
   - ./nginx/conf.d:/etc/nginx/conf.d
   depends_on:
   - app