package com.lab.lab;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

/**
 * 
 * @author ilkovjr
 *
 */
@Controller    // This is a Controller class
@RequestMapping(path="/app") // URL's start with /app after the connection path
public class MainController {
	
	// Needed in order to get the bean called userRepository
	// Which is auto-generated by Spring and will handle the data.
	@Autowired
	private CarRepository carRepo;

	// @ResponseBody means the returned String is the response
	// @RequestParam is a parameter from the GET or POST request
	@GetMapping(path = "/add")
	public @ResponseBody String addNewCar(@RequestParam String make, @RequestParam String model, @RequestParam int yearMade) {

		// Making a car object and setting the params
		//from the request call
		Car c = new Car();
		c.setMake(make);
		c.setModel(model);
		c.setYearMade(yearMade);

		// Saving the object to the carRepo
		carRepo.save(c);
		return "Saved";
	}

	// This returns a JSON or XML with the cars
	@GetMapping(path = "/cars")
	public @ResponseBody Iterable<Car> getAllCars() {
		return carRepo.findAll();
	}

}
